# Generated by Django 4.0.5 on 2022-07-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=75)),
                ('company_password', models.CharField(max_length=75)),
            ],
        ),
    ]
