# Generated by Django 4.0.6 on 2022-07-21 12:54

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jorden_Admin', '0005_watchoutpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingactionable',
            old_name='company',
            new_name='company_property',
        ),
        migrations.RenameField(
            model_name='watchoutpoint',
            old_name='company',
            new_name='company_property',
        ),
        migrations.CreateModel(
            name='CompanyContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_company', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('what_company', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('key_info', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('any_specific', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('company_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyContext', to='jorden_Admin.listofcompanies')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.TextField()),
                ('locality', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('pin_code', models.CharField(max_length=6)),
                ('company_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyAddress', to='jorden_Admin.listofcompanies')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=100)),
                ('industry_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('company_email', models.CharField(max_length=30, null=True)),
                ('gst_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('pf_number', models.CharField(max_length=20, null=True)),
                ('esic_number', models.CharField(max_length=20, null=True)),
                ('company_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Companie', to='jorden_Admin.listofcompanies')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=15)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('company_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BankDetail', to='jorden_Admin.listofcompanies')),
            ],
        ),
    ]
