# Generated by Django 4.0.6 on 2022-07-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jorden_Admin', '0006_rename_company_pendingactionable_company_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetail',
            old_name='company_property',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_property',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='companyaddress',
            old_name='company_property',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='companycontext',
            old_name='company_property',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='watchoutpoint',
            old_name='company_property',
            new_name='company_id',
        ),
    ]
